export const departamentos = [
    { key: "amazonas", text: "Amazonas", value: "Amazonas" },
    { key: "antioquia", text: "Antioquia", value: "Antioquia" },
    { key: "arauca", text: "Arauca", value: "Arauca" },
    { key: "atlantico", text: "Atlántico", value: "Atlántico" },
    { key: "bogota", text: "Bogotá D.C.", value: "Bogotá D.C." },
    { key: "bolivar", text: "Bolívar", value: "Bolívar" },
    { key: "boyaca", text: "Boyacá", value: "Boyacá" },
    { key: "caldas", text: "Caldas", value: "Caldas" },
    { key: "caqueta", text: "Caquetá", value: "Caquetá" },
    { key: "casanare", text: "Casanare", value: "Casanare" },
    { key: "cauca", text: "Cauca", value: "Cauca" },
    { key: "cesar", text: "Cesar", value: "Cesar" },
    { key: "choco", text: "Chocó", value: "Chocó" },
    { key: "cordoba", text: "Córdoba", value: "Córdoba" },
    { key: "cundinamarca", text: "Cundinamarca", value: "Cundinamarca" },
    { key: "guainia", text: "Guainía", value: "Guainía" },
    { key: "guaviare", text: "Guaviare", value: "Guaviare" },
    { key: "huila", text: "Huila", value: "Huila" },
    { key: "guajira", text: "La Guajira", value: "La Guajira" },
    { key: "magdalena", text: "Magdalena", value: "Magdalena" },
    { key: "meta", text: "Meta", value: "Meta" },
    { key: "narino", text: "Nariño", value: "Nariño" },
    { key: "norte_santander", text: "Norte de Santander", value: "Norte de Santander" },
    { key: "putumayo", text: "Putumayo", value: "Putumayo" },
    { key: "quindio", text: "Quindío", value: "Quindío" },
    { key: "risaralda", text: "Risaralda", value: "Risaralda" },
    { key: "san_andres", text: "San Andrés y Providencia", value: "San Andrés y Providencia" },
    { key: "santander", text: "Santander", value: "Santander" },
    { key: "sucre", text: "Sucre", value: "Sucre" },
    { key: "tolima", text: "Tolima", value: "Tolima" },
    { key: "valle", text: "Valle del Cauca", value: "Valle del Cauca" },
    { key: "vaupes", text: "Vaupés", value: "Vaupés" },
    { key: "vichada", text: "Vichada", value: "Vichada" }
  ];